#pragma once

#include <MIDI.h>
#include <Adafruit_TinyUSB.h>
#include <SoftwareSerial.h>
#include <Wire.h>
//from the pico sdk
extern "C" {
    #include "pico/util/queue.h"
}

#include "commonEnums.h"

/*

Stepchild MIDI class!

It's a little ugly because I can't store all the MIDI interface objects
in an array together (they're all different datatypes that are template types, super abstract but 
I bet it's possible)

If this is ever too messy, I could store each interface object (MIDI1, MIDI2...) as a pointer
But I think I would need different pointers for the Hardware/Software/USB interfaces

The headless MIDI class works totally differently.

*/

//MIDI callbacks for different play modes
void handleStop_playing();
void handleClock_playing();
void handleStart_playing();
void handleClock_recording();
void handleStart_recording();
void handleStop_recording();
void handleNoteOn_Recording(uint8_t channel, uint8_t note, uint8_t velocity);
void handleNoteOff_Recording(uint8_t channel, uint8_t note, uint8_t velocity);
void handleCC_Recording(uint8_t channel, uint8_t cc, uint8_t value);
void handleCC_Normal(uint8_t channel, uint8_t cc, uint8_t value);
void handleNoteOn_Normal(uint8_t channel, uint8_t note, uint8_t velocity);
void handleNoteOff_Normal(uint8_t channel, uint8_t note, uint8_t velocity);
void handleStart_Normal();
void handleStop_Normal();
void handlePB(uint8_t ch, int val);


//Custom MIDI Library settings (see: https://github.com/FortySevenEffects/arduino_midi_library/wiki/Using-custom-Settings)
struct StepchildMIDISettings:public midi::DefaultSettings{
  static const bool UseRunningStatus = false;
  static const bool HandleNullVelocityNoteOnAsNoteOff = true;
  static const bool Use1ByteParsing = true;
  static const unsigned SysExMaxSize = 16;//Stepchild doesn't receive SysEx as of now, but will this crash it?
  static const long BaudRate = 31250;//This one isn't documented, but you need it. Default val is 31250, will this work w/ USB?
};

/*

multicore midi buffer using the queue object provided by the pico sdk to pass midi messages from core 1 into core 0
This is an experiment to see if it helps prevent tUSB disconnects!

you should have a way of handling each of the possible messages

good resource for the midi spec:
https://users.cs.cf.ac.uk/dave/Multimedia/node158.html#:~:text=MIDI%20message%20includes%20a%20status%20byte%20and%20up%20to%20two%20data%20bytes.&text=The%20most%20significant%20bit%20of,remaining%20bits%20identify%20the%20message.

*/

typedef struct {
    uint8_t data[3];//holds the 3 data bytes of the midi message
} multicore_midi_message_t;

#define MULTICORE_MIDI_BUFFER_SIZE 16

class StepchildMIDI{
  public:

  //channels are 0 indexed here, but in stepchild world
  //channels are 1-16, with 0 indicating global channel
  uint16_t midiChannelFilters[5] = {0b1111111111111111,0b1111111111111111,0b1111111111111111,0b1111111111111111,0b1111111111111111};
  uint8_t midiMuteSettings = 0b00000000;
  queue_t multicoreBuffer;
  bool queueIsFull = false;

  enum MULTICORE_MIDI_MESSAGE:unsigned short int{
    //channel messages
    NOTE_OFF = 0x80,
    NOTE_ON = 0x90,
    CONTROL_CHANGE = 0xB0,
    PROGRAM_CHANGE = 0xC0,
    PITCH_BEND = 0xE0,
    ALL_OFF = 0x7B, //not actually a status byte, it's the 1st data byte of a CC message
    //system messages
    MIDI_CLOCK = 0xF8,
    MIDI_START = 0xFA,
    MIDI_CONTINUE = 0xFB,
    MIDI_STOP = 0xFC
  };

  StepchildMIDI();
  bool pushMessageToQueue(multicore_midi_message_t* message);
  void init();
  //Control Change
  void sendCC(uint8_t controller, uint8_t val, uint8_t channel);
  //Program Change
  void sendPC(uint8_t port, uint8_t val, uint8_t channel);
  void noteOn(uint8_t pitch, uint8_t vel, uint8_t channel);
  void noteOff(uint8_t pitch, uint8_t vel, uint8_t channel);
  void allOff();
  void sendClock();
  void sendStop();
  void sendStart();
  //function that gets called from core0 to send out midi data generated by core1
  void processCore1Messages();
  void read();
  bool isThru(uint8_t output);
  void setThru(uint8_t output, bool state);
  void allChannelsOff(uint8_t whichPort);
  void allChannelsOn(uint8_t whichPort);
  void setAllChannels(bool state, uint8_t whichPort);
  //checks if a port is filtering a channel
  bool isChannelActive(uint8_t whichChannel,uint8_t whichPort);
  bool isMuted(uint8_t whichPort);
  void toggleMute(uint8_t whichPort);
  void toggleThru(uint8_t output);

  void setMidiChannel(uint8_t channel, uint8_t output, bool status);
  //toggles the channel on an output, and returns its new value
  bool toggleMidiChannel(uint8_t channel, uint8_t output);
  void muteMidiPort(uint8_t which);
  void unmuteMidiPort(uint8_t which);
  void toggleMidiPort(uint8_t which);
  void sendThruOn(uint8_t channel, uint8_t note, uint8_t vel);
  void sendThruOff(uint8_t channel, uint8_t note);
  void sendThruCC(uint8_t channel, uint8_t cc, uint8_t val);
  void sendThruPB(uint8_t ch, int val);
  void disconnectMIDICallbacks();
  void setMIDICallbacks(PlayState state);
};